### ISSUE TITLE
Can't install cypari2

### ISSUE THREAD

**Issue by liammulh** [numberscope/backscope#47]
As of this writing (https://github.com/numberscope/backscope/commit/aeb7595e03e3fac502be666b259d0d5685131f90), I think there might be something (multiple things?) wrong with `requirements.txt`. Then again, it might just be a "Liam issue".

### Problems I've encountered and their and solutions

(These are mostly notes to myself.)

This isn't a comprehensive list, but here are the big ones:

* Problem: You need the `gp` binary.
  * Solution: This can be solved by `sudo apt install pari-gp`, but this solution leads to more problems down the line. Instead, I recommend `sudo apt install sagemath` instead.
* Problem: `cypari2` metadata generation fails because a `pari.desc` file is missing.
  * Solution: I've found that `sudo apt install sagemath` fixes this.
* Problem: Can't build wheel for `cypari2`.
  * Solution: `pip install cysignals` separately from `pip install -r requirements.txt`. `¯\_(ツ)_/¯`
* Problem: Can't build wheel for `numpy`.
  * Solution: Upgrade `numpy` from 1.20.0 to 1.23.2 by modifying `requirements.txt`. (Or was it by `pip install numpy` which gets the latest version?)

UPDATE: The solutions I list in the details above work (for me) on both Linux and macOS.

Could someone do the following:

1. Blow away your `.venv` directory: `rm -rf .venv`
2. Blow away your `pip` cache: `python3 -m pip cache purge`
3. Create a new `.venv`: `virtualenv -p python3 .venv`
4. Activate: `source .venv/bin/activate`
5. Install requirements: `pip install -r requirements.txt`

This will help me determine if there's an issue with `requirements.txt`.

**Comment by gwhitney** [comment]
In my experiment in my home directory, and apparently in the scope installation for production, I found that I had to re-run the compilation of cypari one more time after the initial install, i.e., execute `pip install --force cypari` again after the `pip install -r requirements.txt`. Should we put this in the install documentation, or chalk it up to some transitory library problem that will go away?

**Comment by liammulh** [comment]
Whether it goes into the docs depends on whether it is system-dependent.

I believe this isn't system-dependent. (Re-installing cypari2 after `pip install -r requirements.txt` was one of the solutions to one of the problems I encountered when trying to install backscope on fresh systems.)

**Comment by gwhitney** [comment]
Since I don't see how it would really hurt, I suggested we just go ahead and put in the extra step as part of #56. Thoughts?

**Comment by gwhitney** [comment]
I think this is now resolved as of the merge of #56. Should we close?

**Comment by liammulh** [comment]
Re-opening because this unfortunately still an issue.

Re-posted from Slack:

I'm working on my CI PR, and unfortunately I'm running into issues with installing cypari2 on GitHub's hosted runner.

For context, take a look at the [workflow file](https://github.com/numberscope/backscope/blob/ci/.github/workflows/continuous_integration.yml).

I removed cypari2 from requirements.txt (otherwise not all of the dependencies are installed -- the step just quits once it hits an error even if you set `continue-on-error: true` in the YAML workflow file).

In a separate step, I install pari-gp (otherwise installing cypari2 would error, complaining about there being no `gp` in `PATH`), then attempt install cypari2. This attempt fails; it errors with `error: [Errno 2] No such file or directory: '/usr/share/pari/pari.desc'`. I set this step to `continue-on-error: true`, so ultimately the job succeeds, however the error is still there, and cypari2 isn't installed.

One of the solutions I discovered for the above error in https://github.com/numberscope/backscope/issues/47 was to install SageMath, but that's a large library, and we wouldn't want to waste our GitHub Actions minutes doing this. (Or would we?)

Not sure where to go from here. Technically the GitHub workflow is passing (because of `continue-on-error: true`), so I could submit a PR, but for future tests, we'll need to be able to install cypari2.

Here's a link to a workflow run where I try to install pari-gp before cypari2: https://github.com/numberscope/backscope/actions/runs/3331040335

Here's a link to a workflow run where I try to install SageMath (there was an error for this one as well -- albeit one that could probably be fixed): https://github.com/numberscope/backscope/actions/runs/3331132934

You can run these with debug log if you're interested. See the pictures.

<img width="600" alt="re-run" src="https://user-images.githubusercontent.com/60749003/198098389-9def41a4-10a6-4f21-815f-47df3b0fe9e9.png">

<img width="600" alt="debug" src="https://user-images.githubusercontent.com/60749003/198098448-d496bc4b-0681-4b59-a253-e5cb7ef6a6de.png">

**Comment by katestange** [comment]
I would really avoid installing Sage if it all possible.  A proper install takes a loooong time and it's all kinds of overhead we don't need and it's constantly updated.  On the other hand, maybe it's not avoidable.

**Comment by gwhitney** [comment]
I am sure this is possible without sage. I will look when I get a chance.

**Comment by liammulh** [comment]
I did a bit of work on this in https://github.com/numberscope/backscope/commit/4a47fa9bf0fb3d871bb3537cbe3b35d685326c7e, https://github.com/numberscope/backscope/commit/1904b4983c3bc882ff4cfeb65c503e0091c8b12b, and https://github.com/numberscope/backscope/commit/dd2bbd978f5ae8c70685de7850756fb6a111cc8d.

Specifically, I tried installing cypari2's dependencies explicitly as a sanity check:

```
      - name: Attempt to install cypari2
        continue-on-error: true
        run: |
          sudo apt install pari-gp
          source .venv/bin/activate
          pip install cysignals
          pip install Cython
          pip install cypari2
```

From cypari2's README:

>Using pip
>
>Requirements:
>
>    PARI/GP >= 2.9.4 (header files and library)
>    Python >= 3.6
>    pip
>    [cysignals](https://pypi.python.org/pypi/cysignals/) >= 1.7
>    Cython >= 0.29
>
>Install cypari2 via the Python Package Index (PyPI) via
>
>$ pip install cypari2 [--user]

We seem to be following their instructions perfectly, and yet we are getting:

```
 Collecting cypari2
  Downloading cypari2-2.1.3.tar.gz (127 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.3/127.3 kB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-o1kymbju/cypari2.egg-info
      writing /tmp/pip-pip-egg-info-o1kymbju/cypari2.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-o1kymbju/cypari2.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-pip-egg-info-o1kymbju/cypari2.egg-info/requires.txt
      writing top-level names to /tmp/pip-pip-egg-info-o1kymbju/cypari2.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-o1kymbju/cypari2.egg-info/SOURCES.txt'
      error: [Errno 2] No such file or directory: '/usr/share/pari/pari.desc'
      [end of output]
```

**Comment by gwhitney** [comment]
cypari installations no longer appear to be a problem.
